baseURL: https://blog.chensoul.com/
title: ChenSoul
theme: den
enableRobotsTXT: true
enableEmoji: true
hasCJKLanguage: true
preserveTaxonomyNames: true
rssLimit: 100
page_view_conter: true
enableRelated: true

# Copyright, appears in the footer
# copyright = ""             # default: author.name

# Pagination
# number of entries per page for archives, tags and categories
# since we don't have list view, recommend a large value
paginate: 20
paginatePath: "page"

# Syntax Hightlight
PygmentsCodeFences: true
PygmentsUseClasses: true    # required for shhighlight shortcode

# service plugins
disqusShortname: ""         # disqus_shortname
googleAnalytics: ""         # UA-XXXXXXXX-X

# language support # en / zh / other... translations present in i18n/
defaultContentLanguage: "zh"           # Default language to use
defaultContentLanguageInSubdir: true

permalinks:
  posts: /posts/:slug/
  categories: /categories/:slug/
  tags: /tags/:slug/
  pages: /:slug/

author:
  name: chenshu
sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml
params:
  since: "2020"
  rssFullContent: true
  keywords:
    - devops
    - programming
  description: Programming | Devops
  logoTitle: ChenSoul
  siteLogoImage: images/fly.png

  # headerTitle = "chenshu"                   # default: title
  headerImage: images/background.webp
  showAuthorCard: true
  showMenuLanguages: true
  autoLoadComments: false
  paginateOriginalStyle: true

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse: 2006-01-02
  google_verification: "D8XBzUhT4irNUQLKut79HFni0v3Xow4FY-oxUcsUlVk"

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS: []
  customJS: []

markup:
  goldmark:
    renderer:
      unsafe: true


# ------------------------------------- #
# ---- Related Articles --------------- #
# ------------------------------------- #
related:
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold: 50

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer: true

  # Will lower case keywords in both queries and in the indexes.
  toLower: true

  indices:
    - name: categories
      weight: 200
    - name: keywords
      weight: 150
    - name: tags
      weight: 100
languages:
  zh:
    languageCode: zh
    languageName: 中文
    contentDir: content
    weight: 1
    params:
      description: Devops | Programming
    menu:
      main:
        - name: 思考
          weight: 10
          identifier: idea
          url: categories/idea/
      social:
        - name: Telegram
          weight: 10
          identifier: telegram
          url: https://t.me/chenshu_eth
        - name: Twitter
          weight: 20
          identifier: twitter
          url: https://twitter.com/chenshu_eth
        - name: BiliBili
          weight: 40
          identifier: bilibili
          url: https://space.bilibili.com/699805065/
      links:
        - name: GitHub
          weight: 10
          identifier: github
          url: https://github.com/chensoul
        - name: Services
          weight: 20
          identifier: services-status
          url: https://uptime.chensoul.com/status/services
        - name: Analytics
          weight: 30
          identifier: chensoul-analytics
          url: https://data.pseudoyu.com/share/8YKX7FUa/pseudoyu-blog